### ISSUE TITLE
Add "remove unused imports" hook to pre-commit hooks

### ISSUE THREAD

**Issue by WiscEvan** [KwanLab/Autometa#330]
Add hook to pre-commit hooks config to remove unused imports in python files.

See https://pre-commit.com/hooks.html (cmd+F `pycln`) for list of pre-commit hooks.

This looks promising: https://github.com/hadialqattan/pycln

The relevant code for `.pre-commit-config.yaml` 🍝  https://hadialqattan.github.io/pycln/#/?id=integrations

Append to `.pre-commit-config.yaml`:

```yaml
- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.5 # Possible releases: https://github.com/hadialqattan/pycln/releases
  hooks:
    - id: pycln
```
